### PR TITLE
Specify Node v4.2.3

### PR DESCRIPTION
**Pull request by SiAdcock**
Since we're using ES6 in the Gulpfile, it's important to specify that Node v4 is required. If a contributor uses an earlier version of Node they currently get a syntax error, which is not a great experience.

I've also tidied up the README a little bit.

### CODE REVIEW

**Comment by SiAdcock** [comment]
A bit of background from `.nvmrc`:

nvm is a version manager for node, allowing you to easily switch between Node versions on your dev machine.

You can get a Windows version here:

https://github.com/coreybutler/nvm-windows

I highly recommend having something that allows you to manually test your JS code in multiple Node versions.

**Comment by Jameskmonger** [comment]
@SiAdcock what about writing the gulp file in TypeScript and allowing the user to compile it how they like?

**Comment by SiAdcock** [comment]
I think certain opinions and conventions need to be enforced, unless you intend to support all the way down to node v0.10 or something. If you give contributors freedom to use whatever version of node they like, you're asking for trouble in my opinion :smile: 

I have no problem with the Gulpfile being written in TypeScript, but you'd need to provide a way for the contributor to transpile it down to JS (such as in the `scripts` section of `package.json`)

**Comment by Jameskmonger** [comment]
What I've done in some of my other projects is have `typescript` as a dev dependency, and have an "npm run gulp" script which executes the TypeScript compiler on the gulpfile. I would like to support all versions of node in terms of compilation and using the library - it seems a shame to prevent them if it's just the gulp file standing in the way!

**Comment by SiAdcock** [comment]
Fair enough, I can't think of any downsides! I'm just anti-legacy, it's a character flaw :) Feel free to close this

**Comment by Jameskmonger** [comment]
@SiAdcock  Do you know if there is any way to just merge in your README.md changes?

**Comment by SiAdcock** [comment]
You'll need to pull down my branch, create a new local branch, cherry pick the changes you want into the new branch, then merge the new branch into master.

It's a bit fiddly, but good practice! Cherry picking can be very useful.

[http://mispdev.blogspot.co.uk/2013/02/github-cherry-picking-commits-from-pull.html?m=](http://mispdev.blogspot.co.uk/2013/02/github-cherry-picking-commits-from-pull.html?m=1)

**Comment by Jameskmonger** [comment]
README changes merged in 1470de2b845fa072463b136c4d2414fa0228f696

Thanks, Simon!

**Pull request closed without merging**
