### PR TITLE
Flatten module path

### PR DESCRIPTION
**Pull request by SiAdcock**
Big directory structure update incoming.

1. Changed the build output directory to be the package root directory, rather than `build`
2. Flattened the superfluous `courtroom` subdirectory in `src`
3. Renamed `courtroom.ts` to `index.ts` to take advantage of CommonJS's index path resolution
4. Updated `index.ts` to export the `Courtroom` class directly, rather than a `CourtroomModule` that exposes the `Courtroom` class

**Why do such things?**

As it stands, the way to require the main Courtroom constructor function into a CommonJS module is bordering on comical:

```javascript
const Courtroom = require('courtroom/build/courtroom/courtroom').Courtroom; //enough courtroom?
const c = new Courtroom();
```

As a result of these changes, the require is much more streamlined:

```javascript
const Courtroom = require('courtroom');
const c = new Courtroom();
```

Let me know if you need me to break this down into smaller PRs.

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Thanks Simon, this is great! Really appreciate the work.

**Comment by SiAdcock** [comment]
Haha just realised in the README, `issues` should be a `let` not a `const` :sweat_smile:

Happy to publish to npm? If so, I promise my next PR will be actual functionality rather than developer experience (well, once we've killed that RequireJS dependency)!

**Comment by Jameskmonger** [comment]
Just updated the README for you! I'll get it published to NPM when I get home :+1: Thanks again! :fireworks:

**Comment by SiAdcock** [comment]
Thanks man, that syntax issue in the README was proper bugging me! Don't forget to verbump so npm will pick up the latest version :smile:

**Comment by Jameskmonger** [comment]
Hey @SiAdcock, just looking at pushing to NPM now and I've noticed that everything now gets built into the root folder. This is different to how I've seen other libraries do it, which typically have the index.js file in the root folder with the others in a `bin` folder. What do you think?

**Pull request merged**
